version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: fhir
      POSTGRES_PASSWORD: fhirpass
      POSTGRES_DB: fhir
    ports:
      - "5432:5432"

  fhir:
    image: hapiproject/hapi:latest
    ports:
      - "8080:8080"

  kong:
    image: kong:3.7
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./kong/kong.yml:/kong/kong.yml
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001

  n8n:
    image: n8nio/n8n:1.69.2
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=adminpass

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    ports:
      - "8082:8082"
    command: ["start-dev"]
